name: RuiKQ的博客
description: 左手画笔，右手键盘
meta_description: "RuiKQ的博客, 左手画笔，右手键盘"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://yourblog-domain.com'

# Details for the RSS feed generator
url:            'http://ruikq.github.io'
author:         'RuiKQ'
